language: ruby
rvm:
- 2.3.3
before_script:
- wget https://github.com/tdewolff/minify/releases/download/v${MINIFY_VERSION}/minify_2.3.4_linux_amd64.tar.gz
- tar xvzf minify_${MINIFY_VERSION}_linux_amd64.tar.gz minify
- "./minify -o jekyll/js/site.min.js jekyll/js"
- "./minify -o jekyll/js/main.css jekyll/css"
- rm -rf jekyll/js/app.js jekyll/js/bootrap3_player.js jekyll/js/rgbaster.min.js jekyll/js/xt.js
  jekyll/css/bootstrap3_player.css jekyll/css/one-page-wonder.css jekyll/css/xtradio.css
- chmod +x ./tests/cibuild.sh
script: "./tests/cibuild.sh"
branches:
  only:
  - master
env:
  global:
  - MINIFY_VERSION=2.3.4
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: DzJxGjRNKnCo+HmRUhiVmQ3BUI25t3LtbOx/b1LVoDJ8RDtYmBreR+EQaLOH6jF7PLw8ou5u+3ovaOcvpapDGpZBRJ7rbIw6U5Qqc4Gay5Kg1X0B9rtwV7x2CJHRM0ZHArS3nMafRks0hYctehbxJxjo2jH4fL2Eh70Hy6hXqVQmcf5yCsAUwWBYk1+p6DjhQtEGs/qVsdtmlKCSS2F2rKf6O1OjPSyKg4lVR6v+n0ijLHJcyvhhmV/HFlZchBhZyO1nosYZC8oBdG+wDMiZEai5PcIp/7gF58vWWacxYJH2aMS7WY5A0ayg8xsTwXtfg/ZOPOCCuI8qnZCu8yB2Liu2gOTKfeCNTOv1zGqV74PE0pcbOgopqt8Ayem/eHwyDVMntWrxbyx7gKhkgZ6atoqxHwUTdHmq8909AdbW1jmAisW6v2M68KS6mYtV0isnbE2SLYrd6S6d9iLeJZ+5uQ8AJV+2uFo2tSS20WqCu2A0j7OAQXPuMO3FQkRpG1PKJyVJJ1YhYDlvMbszN9VaX0TnQ5Ti0YoKvlWFMF52W3cQY3GeHUTNZruaaQyIDmZEjxNeG4EyDdPJZJjpRiR9sEojfsJeYXENqdHlQTsDuiYNfiv2zAP3L6wJ9BsU0PKgCYVlM/yHRp0+J24F5jvSMSRbVDwSTCYkk0v+EbZZ0BE=
  - secure: mWEp/IkVhc9K4jdphYGqvdwQXmJ0b/zgbrP3La1Jb41HJHoCNf1HUerZlavPLKLKVvd1wxC0K0UdSG1BVAKcxDbPCiZ5xsjPm7wcGtw1fl/QgiDtm4K/nm30XwjpYFlEq3DvOmXgMh3xPaOt/5Z9ba5AjVqxtQiDgM1uVvCOzjpnhcDGAnITjbFofgjH1zH62k484cTUYjZzSRQ9Pm2F+PSojouIbhYeS5lXA19jE3JDFDmUj2pLQVY0joZWMjq4oFJ6KxMgKN6tVwSRkTuYK0mNAiaqFrn3/zRKk2YCdv9ifar5LkrBwN65aCH9utgho/UiRubxQtoIdWCbamBTkfMgmMlc3sv8Zk7rmKQZfSZ/i54QCWREfBw2FFamY6iIlIrOXL3TeuuGsqJfBZHTwp1ekMfSaT/zxSqzlKvnVd1/N+QfMQm4/Ek5+a5wcCNAhaEHTW9Cwd5Q1p2g/VzLIgCIWLA34d6CAtTL12oH++Plv6zhR2yIgtGrE86X1ZEO++XYcxycr4a+yg9Yh4WM3/CDG0A2LzhT9zpBrKsbnC8bMIbvXqXdvxDK7ixxgt0BNiycy8kPbezcasT+1+TwW4IaI6n1sESrlupKS9hX5t+Wfc9MhnNXFnOcHbr+OsArSdCdvmTpO/IJrwYkR+Ta7JQ5c0qf11r9/mus6iD9Gms=
notifications:
  email: false
  slack:
    secure: wiWFrSYLOp/UGHFpemvQTwZ87WclsdriRbyDWYmCysH1kmtHikh9hSIHWmHdiot5giUwLe9KPKkEMRLnUfgNg47h4cLogPluL01c3mgXM4Vt1uH2ZIKEwh2ezzMJAgKWNV56zOcUEldWRtBYIQXVfVcpcjydeTnRdjSmE14d4cJOQWAb3ysBdCJ0u/iP3YPrLTC+64mXtFYqE4CytL6koPvVLd4Nz8tOaih7Egv0I1PbWGROnolOnyHtq8PHiDcixBqJ9sktaamq8ImLolnRMQCNW3mmCZGysEPdbHcoGIIfIxo0D1P4uDFlZqzCsI3eRC0Q0i3vZfF/ha+fBCTaU2mLnjd5a1ABvZpncljpjbrXR1hflwsFrSHai8wuH2WGt7QVwfsWe8D9RbdeP39lq6DM1QFMV3izmJ0t2c+54j5ksHcqCbH/3dWtI3DJIweNa/I9A6/2YNkccX27eVkXqW5zco8ULz7CB1SD6L+hzcJAng1U0T3i6ecclrIfhfDZn3eE+8ktX2mvX+o39UZjsOHwcFZcJ54nXr+sv6Qo06EXEhtWlOcg+BQGH6F3b+slpHpi9DjDP7vviIoAaMVNrfmXXKfFYjqQhX3bhQIwbXOmVsh7Try6pGOEVhZp09s8VJA3PVYdLtWgsVexNZRIZd5UDKbNPHa1TOR3Ejb2HmM=
after_success:
- docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
- export REPO=xtradio/xtradio.org
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- docker build -f Dockerfile -t $REPO:latest .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
