language: ruby
rvm:
- 2.3.3
before_script:
  - wget https://github.com/tdewolff/minify/releases/download/v${MINIFY_VERSION}/minify_2.3.4_linux_amd64.tar.gz
  - tar xvzf minify_${MINIFY_VERSION}_linux_amd64.tar.gz minify
  - ./minify -o jekyll/js/site.min.js jekyll/js
  - ./minify -o jekyll/js/main.css jekyll/css
  - rm -rf jekyll/js/app.js jekyll/js/bootrap3_player.js jekyll/js/rgbaster.min.js jekyll/js/xt.js jekyll/css/bootstrap3_player.css jekyll/css/one-page-wonder.css jekyll/css/xtradio.css
  - chmod +x ./tests/cibuild.sh
script: "./tests/cibuild.sh"
branches:
  only:
  - master
env:
  global:
  - MINIFY_VERSION=2.3.4
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: DzJxGjRNKnCo+HmRUhiVmQ3BUI25t3LtbOx/b1LVoDJ8RDtYmBreR+EQaLOH6jF7PLw8ou5u+3ovaOcvpapDGpZBRJ7rbIw6U5Qqc4Gay5Kg1X0B9rtwV7x2CJHRM0ZHArS3nMafRks0hYctehbxJxjo2jH4fL2Eh70Hy6hXqVQmcf5yCsAUwWBYk1+p6DjhQtEGs/qVsdtmlKCSS2F2rKf6O1OjPSyKg4lVR6v+n0ijLHJcyvhhmV/HFlZchBhZyO1nosYZC8oBdG+wDMiZEai5PcIp/7gF58vWWacxYJH2aMS7WY5A0ayg8xsTwXtfg/ZOPOCCuI8qnZCu8yB2Liu2gOTKfeCNTOv1zGqV74PE0pcbOgopqt8Ayem/eHwyDVMntWrxbyx7gKhkgZ6atoqxHwUTdHmq8909AdbW1jmAisW6v2M68KS6mYtV0isnbE2SLYrd6S6d9iLeJZ+5uQ8AJV+2uFo2tSS20WqCu2A0j7OAQXPuMO3FQkRpG1PKJyVJJ1YhYDlvMbszN9VaX0TnQ5Ti0YoKvlWFMF52W3cQY3GeHUTNZruaaQyIDmZEjxNeG4EyDdPJZJjpRiR9sEojfsJeYXENqdHlQTsDuiYNfiv2zAP3L6wJ9BsU0PKgCYVlM/yHRp0+J24F5jvSMSRbVDwSTCYkk0v+EbZZ0BE=
  - secure: mWEp/IkVhc9K4jdphYGqvdwQXmJ0b/zgbrP3La1Jb41HJHoCNf1HUerZlavPLKLKVvd1wxC0K0UdSG1BVAKcxDbPCiZ5xsjPm7wcGtw1fl/QgiDtm4K/nm30XwjpYFlEq3DvOmXgMh3xPaOt/5Z9ba5AjVqxtQiDgM1uVvCOzjpnhcDGAnITjbFofgjH1zH62k484cTUYjZzSRQ9Pm2F+PSojouIbhYeS5lXA19jE3JDFDmUj2pLQVY0joZWMjq4oFJ6KxMgKN6tVwSRkTuYK0mNAiaqFrn3/zRKk2YCdv9ifar5LkrBwN65aCH9utgho/UiRubxQtoIdWCbamBTkfMgmMlc3sv8Zk7rmKQZfSZ/i54QCWREfBw2FFamY6iIlIrOXL3TeuuGsqJfBZHTwp1ekMfSaT/zxSqzlKvnVd1/N+QfMQm4/Ek5+a5wcCNAhaEHTW9Cwd5Q1p2g/VzLIgCIWLA34d6CAtTL12oH++Plv6zhR2yIgtGrE86X1ZEO++XYcxycr4a+yg9Yh4WM3/CDG0A2LzhT9zpBrKsbnC8bMIbvXqXdvxDK7ixxgt0BNiycy8kPbezcasT+1+TwW4IaI6n1sESrlupKS9hX5t+Wfc9MhnNXFnOcHbr+OsArSdCdvmTpO/IJrwYkR+Ta7JQ5c0qf11r9/mus6iD9Gms=
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    secure: QGX/KihrhG2fi1PkvXimOjhXbUVF1PNCzqPqz/zTfbOga6O08G8MkW72VBWHkqhI7uWteJB3Pj0nMNGH9+/5pHBSlzwohz6zbetHypt0S7UFjH4Yc8aXQXAWO5Z7NKTCDaIW3E+uPuigODy84xOf21dzl08xNOOWx2xMHA53iXOG4ceX3faAM6kQCTCIPrxqFRiXKwn1HDWa7BjYGdYgQZzI6/6TWBsc0K+phvqVRQ0zGDQh84e0oOLhNxNUMvt6q0CCiLOQC6mTMEPmpESRkcBgNj/s9wEcKHnfTRcoLne6UFdoHCOOTbUSavZnTo2AkIvpbK6uwTZHz/J7A0EEkTNbwQgBgFpYcG4vRX5MWmHXnusIHh5GkNLzTmR9Xsdv24xsuA0D8XFXGDYvuqobVkbd4PivuCAqvn5ynHzqQWepr4sx6Atx+q2aArm1g0Rrk01XoTlL3sW1SgP7vbdUnPe/PNgMMOA27yWjAbOByXGrteKTy5ZeFEoIvIhWhWO9d2Tho3pQbpwDfG/PlLXwWj3PdeEc5njDCAWI2xhzpI53JQe+cwslMzO0xPFrCZP9nfyf0yukHmyJ+hmkSh8nLuUtpxKFBq+NkTZTtGH9cfFg8TwoT2m6PVT55BEPsTLNeB7lTS0eNr4Sh7AX+IKYCDKa2+4OyaAKWy+lN2HzZ9E=
after_success:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
  - export REPO=xtradio/xtradio.org
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
    fi`
  - docker build -f Dockerfile -t $REPO:latest .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
