# Site Settings
title: XTRadio.ORG
description: "XTRadio.ORG brings you the best electronic music from across the planet. Free and great tracks for the delight of your ears."
email: contact@xtradio.org
url: "http://xtradio.org"
twitter_username: xtradioofficial
github_username: xtradio
# Build settings
sass:
  sass_dir: _sass
kramdown:
  input: GFM

# XTRadio links
social:
  - name: "playlist"
    url: "http://xtradio.org:8080/live.m3u"
    title: "Download playlist file"
  - name: "apple"
    url: "http://xtradio.org/stream.m3u"
    title: "Open Radio in iTunes"
  - name: "tunein"
    url: "https://tunein.com/radio/XTRadio-s182867/"
    title: "Listen on TuneIn"
  - name: "soundcloud"
    url: "https://soundcloud.com/xtradio"
    title: "Follow XTRadio on Soundcloud"
  - name: "youtube"
    url: "https://youtube.com/xtradioorg/live"
    title: "XTRadio on YouTube"
  - name: "facebook"
    url: "https://facebook.com/xtradioorg"
    title: "XTRadio on Facebook"
  - name: "twitter"
    url: "https://twitter.com/xtradioofficial"
    title: "XTRadio on Twitter"
  - name: "mixcloud"
    url: "https://mixcloud.com/xtradio"
    title: "XTRadio on Mixcloud"

# Exclude files
exclude: ['README.md', 
          'docker-compose.yml',
          'LICENSE',
          '.travis.yml',
          'Gemfile',
          'tests']
