# Site Settings
title: XTRadio.ORG
description: "XTRadio.ORG brings you the best electronic music from across the planet. Free and great tracks for the delight of your ears."
email: contact@xtradio.org
url: "http://xtradio.org"
twitter_username: xtradioofficial
github_username: xtradio
# Build settings
sass:
  sass_dir: _sass
kramdown:
  input: GFM

# XTRadio links
social:
  - url: "http://xtradio.org:8080/live.m3u"
    icon: "winamp-icon.png"
    title: "Download playlist file"
  - url: "http://xtradio.org/stream.m3u"
    icon: "itunes-icon.png"
    title: "Open Radio in iTunes"
  - url: "https://tunein.com/radio/XTRadio-s182867/"
    icon: "tunein-icon.png"
    title: "Listen on TuneIn"
  - url: "https://soundcloud.com/xtradio"
    icon: "soundcloud-icon.png"
    title: "Follow XTRadio on Soundcloud"
  - url: "https://youtube.com/xtradioorg/live"
    icon: "youtube-icon.png"
    title: "XTRadio on YouTube"
  - url: "https://facebook.com/xtradioorg"
    icon: "fb.png"
    title: "XTRadio on Facebook"
  - url: "https://twitter.com/xtradioofficial"
    icon: "tw.png"
    title: "XTRadio on Twitter"
  - url: "https://mixcloud.com/xtradio"
    icon: "mixcloud-icon.png"
    title: "XTRadio on Mixcloud"
  - url: "https://github.com/xtradio"
    icon: "github-icon.png"
    title: "XTRadio Code on Github"
# Exclude files
exclude: ['README.md',
          'CODE_OF_CONDUCT.md',
          'docker-compose.yml',
          'LICENSE',
          '.travis.yml',
          'Gemfile',
          'tests']
